### ISSUE TITLE
disconnect connection

### ISSUE THREAD

**Issue by naimimohammad** [processone/rtb#7]
I run test with below rtb.yml configurations
```yaml
scenario: xmpp
interval: 3 
capacity: 90000
#certfile: cert.pem
starttls: false
csi: false
mam: false
#sm: false
roster: false
http_upload_interval: false
proxy65_interval: false
gnuplot: /usr/bin/gnuplot
jid: ***%@***
password: ***%

servers:
   - tcp://20.20.1.244:5222

www_port: 8080
bind:
        - 20.20.1.1
        - 20.20.1.2
        - 20.20.1.3
        - 20.20.1.4 
        - 20.20.1.5

reconnect_interval: 5
```
but after my connection reached to 70000 about 10000 connection failed and my current connection be 60000 and my session graph show 90000 session .
I wanna to know is this normal action of rtb , means rtb disconnect 30% of its users ?
